version: '3'
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    networks:
      - go-api-network
    ports:
      - 3000:3000

volumes:
  postgres:


networks:
  go-api-network:
    name: go-api
    driver: bridge
