version: '3'
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    networks:
      - go-api-network
    environment:
      API_PORT: 5555
      GIN_MODE: release
    ports:
      - 5555:5555

networks:
  go-api-network:
    name: go-api
    driver: bridge
